blueprint:
  name: Extinction automatique lumière
  description: >
    Éteint automatiquement une lumière après qu'elle soit restée allumée pendant 
    une durée déterminée, peu importe la façon dont elle a été activée. 
    Cela sert de "garde-fou" si un capteur de mouvement reste bloqué ou si 
    une lumière est oubliée.
  domain: automation
  input:
    target_light:
      name: Lumière cible
      description: La lumière ou l'interrupteur que vous souhaitez surveiller.
      selector:
        entity:
          domain: 
            - light
            - switch
    off_delay:
      name: Délai avant extinction (heures)
      description: Combien d'heures la lumière doit rester allumée avant d'être éteinte de force.
      default: 1
      selector:
        number:
          min: 1
          max: 24
          unit_of_measurement: h
          mode: box

mode: restart

trigger:
  - platform: state
    entity_id: !input target_light
    from: "off"
    to: "on"

action:
  - delay:
      hours: !input off_delay
  - service: homeassistant.turn_off
    target:
      entity_id: !input target_light