blueprint:
  name: Sécurité extinction automatique lumière
  description: >
    Éteint automatiquement une lumière après un délai défini en heures et envoie 
    une notification si l'extinction est déclenchée par la sécurité.
  domain: automation
  input:
    target_light:
      name: Lumière cible
      description: La lumière ou l'interrupteur à surveiller.
      selector:
        entity:
          domain: 
            - light
            - switch
    off_delay:
      name: Délai avant extinction (heures)
      description: Délai avant l'extinction automatique.
      default: 1
      selector:
        number:
          min: 0.1
          max: 24
          step: 0.1
          unit_of_measurement: h
          mode: box
    notify_device:
      name: Appareil pour la notification
      description: Appareil mobile qui recevra l'alerte de sécurité.
      selector:
        device:
          filter:
            - integration: mobile_app

mode: restart

trigger:
  - platform: state
    entity_id: !input target_light
    from: "off"
    to: "on"

action:
  - variables:
      light_entity: !input target_light
  - wait_for_trigger:
      - platform: state
        entity_id: !input target_light
        to: "off"
    timeout:
      hours: !input off_delay
    continue_on_timeout: true
  - if:
      - condition: state
        entity_id: !input target_light
        state: "on"
    then:
      - service: homeassistant.turn_off
        target:
          entity_id: !input target_light
      - domain: mobile_app
        type: notify
        device_id: !input notify_device
        title: "Sécurité lumière"
        message: "La lumière {{ state_attr(light_entity, 'friendly_name') }} a été éteinte automatiquement."