blueprint:
  name: Philips Hue Dimmer v2 (MQTT - Dynamic Scenes)
  description: >
    Contrôle une lumière avec l'interrupteur Philips Hue Dimmer v2 (RWL022) via Zigbee2MQTT (Device Triggers).
    Supporte le cycle de jusqu'à 5 scènes via le bouton Hue.
    
    Pré-requis :
    - Un interrupteur RWL022 appairé via Zigbee2MQTT.
    - (Optionnel) Un Helper "Input Number" (Nombre) pour suivre le cycle.
      - Min: 1
      - Max: 5 (ou plus)
      - Step: 1
      
    Boutons :
    - Power (Haut) : Toggle (Allumer/Éteindre)
    - Plus (Haut-Milieu) : Augmenter la luminosité
    - Moins (Bas-Milieu) : Diminuer la luminosité
    - Hue (Bas) : Cycle entre les scènes définies (si Helper présent)
  domain: automation
  input:
    remote:
      name: Interrupteur Hue Dimmer (Device)
      description: Le périphérique (Device) Hue Dimmer Switch v2 sur MQTT.
      selector:
        device:
          integration: mqtt
          multiple: false
    
    light:
      name: Lumière Cible
      description: La lumière à contrôler.
      selector:
        target:
          entity:
            domain: light

    cycle_helper:
      name: Helper de Cycle (Input Number)
      description: >
        L'entité 'input_number' pour suivre le cycle des scènes.
        (Optionnel) Si non défini, le bouton Hue ne fera rien.
      default: {}
      selector:
        entity:
          domain: input_number
    
    scene_1:
      name: Scène 1
      description: Première scène. (Optionnel)
      default: {}
      selector:
        entity:
          domain: scene
    
    scene_2:
      name: Scène 2
      description: Deuxième scène. (Optionnel)
      default: {}
      selector:
        entity:
          domain: scene
    
    scene_3:
      name: Scène 3
      description: Troisième scène. (Optionnel)
      default: {}
      selector:
        entity:
          domain: scene
          
    scene_4:
      name: Scène 4
      description: Quatrième scène. (Optionnel)
      default: {}
      selector:
        entity:
          domain: scene

    scene_5:
      name: Scène 5
      description: Cinquième scène. (Optionnel)
      default: {}
      selector:
        entity:
          domain: scene

trigger:
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: on_press
    id: "power_press"
    
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: up_press
    id: "dim_up_press"
    
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: up_hold
    id: "dim_up_hold"
    
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: down_press
    id: "dim_down_press"
    
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: down_hold
    id: "dim_down_hold"
    
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: off_press
    id: "hue_press"

action:
  - variables:
      cycle_helper_var: !input cycle_helper
      # Create a list of scenes, filtering out empty ones
      scenes: >
        {% set result = [] %}
        {% set s1 = input_scenes_1 | default(none) %}
        {% set s2 = input_scenes_2 | default(none) %}
        {% set s3 = input_scenes_3 | default(none) %}
        {% set s4 = input_scenes_4 | default(none) %}
        {% set s5 = input_scenes_5 | default(none) %}
        {# We cannot access inputs directly in templates like variables easily without mapping them first #}
        {# Actually, blueprint inputs are passed as variables if we define them in variables block usually, but strict mapping is safest #}
        {# Wait, !input returns the string entity_id. If default is {}, it is not none. #}
        {# Let's map them safely #}
      input_scene_1: !input scene_1
      input_scene_2: !input scene_2
      input_scene_3: !input scene_3
      input_scene_4: !input scene_4
      input_scene_5: !input scene_5
      
      active_scenes: >
        {% set raw_scenes = [input_scene_1, input_scene_2, input_scene_3, input_scene_4, input_scene_5] %}
        {% set ns = namespace(scenes=[]) %}
        {% for s in raw_scenes %}
          {% if s != {} and s != none %}
            {% set ns.scenes = ns.scenes + [s] %}
          {% endif %}
        {% endfor %}
        {{ ns.scenes }}
      
      scene_count: "{{ active_scenes | length }}"

  - choose:
      # Power Button: Toggle
      - conditions:
          - condition: trigger
            id: "power_press"
        sequence:
          - action: light.toggle
            target: !input light

      # Dim Up (Single Press): +10%
      - conditions:
          - condition: trigger
            id: "dim_up_press"
        sequence:
          - action: light.turn_on
            target: !input light
            data:
              brightness_step_pct: 10
      
      # Dim Up (Hold): +20%
      - conditions:
          - condition: trigger
            id: "dim_up_hold"
        sequence:
          - action: light.turn_on
            target: !input light
            data:
              brightness_step_pct: 20

      # Dim Down (Single Press): -10%
      - conditions:
          - condition: trigger
            id: "dim_down_press"
        sequence:
          - action: light.turn_on
            target: !input light
            data:
              brightness_step_pct: -10

      # Dim Down (Hold): -20%
      - conditions:
          - condition: trigger
            id: "dim_down_hold"
        sequence:
          - action: light.turn_on
            target: !input light
            data:
              brightness_step_pct: -20

      # Hue Button: Cycle Scenes (Dynamic)
      - conditions: 
          - condition: trigger
            id: "hue_press"
          - condition: template
            value_template: "{{ cycle_helper_var != none and cycle_helper_var != {} }}"
          - condition: template
            value_template: "{{ scene_count > 0 }}"
        sequence:
          - variables:
              current_val: "{{ states(cycle_helper_var) | int(default=0) }}"
              # scene_count is already integer from length filter
              # Logic: next = current + 1. If next > count, next = 1.
              next_val: >
                {% set val = current_val + 1 %}
                {% if val > scene_count %}
                  {% set val = 1 %}
                {% endif %}
                {{ val }}
              
          - action: input_number.set_value
            target:
              entity_id: !input cycle_helper
            data:
              value: "{{ next_val }}"
          
          - action: scene.turn_on
            target:
              entity_id: "{{ active_scenes[next_val - 1] }}"

mode: restart
max_exceeded: silent
